caption_model: adaatt
input_json: ''
input_fc_dir: ''
input_att_dir: ''
input_label_h5: ''
# base
#input_json: data/cocotalk.json
#input_att_dir: data/cocotalk_att
#input_label_h5: data/cocotalk_label.h5
#input_fc_dir: data/cocotalk_fc
#input_box_dir: data/cocotalk_box
#cached_tokens: coco-train-idxs

learning_rate: 0.0005
learning_rate_decay_start: 0
scheduled_sampling_start: 0

# $start_from
language_eval: 0
save_checkpoint_every: 500
val_images_use: 320

batch_size: 32
max_epochs: 30