caption_model: newfc
input_json: ''
input_fc_dir: ''
input_att_dir: ''
input_label_h5: ''

learning_rate: 0.0005
learning_rate_decay_start: 0
scheduled_sampling_start: 0

# $start_from
language_eval: 0
save_checkpoint_every: 1000
val_images_use: 1000

batch_size: 32
max_epochs: 30